#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: Build luci-app-pushbot-rockchip-armv8

on:
  repository_dispatch:
  workflow_dispatch:

env:
  SDK_URL: https://downloads.openwrt.org/releases/24.10.5/targets/rockchip/armv8/openwrt-sdk-24.10.5-rockchip-armv8_gcc-13.3.0_musl.Linux-x86_64.tar.zst
  PackageName: luci-app-pushbot
  PackageSource_URL: https://github.com/beyondwen/luci-app-pushbot
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install zstd python3-pyelftools $(curl -fsSL https://github.com/P3TERX/Actions-OpenWrt/raw/main/depends-ubuntu-2004)
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Clone source code
      working-directory: /workdir
      run: |
        df -hT $PWD
        wget $SDK_URL
        mkdir /workdir/openwrt
        tar xf openwrt-sdk-* -C /workdir/openwrt --strip-components 1
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: Update feeds
      run: cd openwrt && ./scripts/feeds update -a

    - name: Install feeds
      run: cd openwrt && ./scripts/feeds install -a

    - name: Load custom configuration
      run: |
        cd openwrt
        git clone $PackageSource_URL package/$PackageName
        make defconfig
        echo "CONFIG_PACKAGE_$PackageName=y" >> ./.config

    - name: Compile the package
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make package/$PackageName/compile V=s

    - name: Organize files
      if: success()
      run: |
        cd openwrt/bin/packages/*/base
        echo "PackagePath=$PWD" >> $GITHUB_ENV

    - name: Upload package
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PackageName }}
        path: ${{ env.PackagePath }}/${{ env.PackageName }}_*
